### ISSUE TITLE
Why not auth0?

### ISSUE THREAD

**Issue by levino** [tmaximini/next-10-auth#1]
With auth0 this comes all for free and securely managed with password reset email etc. To test this with next.js and your api you can use my package [mock-jwks](https://www.npmjs.com/package/mock-jwks). Also for context https://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own

**Comment by tmaximini** [comment]
Actually [here I mention](https://github.com/tmaximini/next-10-auth/blob/main/src/util/auth.ts#L8-L13) that the JWT generation and logging in is probably done through a 3rd party service like Firebase or Auth0.
The scope of this repo is more to show different approaches on how to handle user authentication inside of Next.js.
Client-side vs. server-side auth etc. 
And Auth0 is great but definitely does not come "for free" - once you reach a certain amount of users it actually gets pretty expensive.

**Comment by levino** [comment]
Thanks for answering. Closing.
